---
layout: page
title: xwMOOC 기계학습
subtitle: 텍스트 콘솔기반 탐색적 데이터 분석(EDA)
output:
  html_document: 
    toc: yes
    keep_md: yes
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---
 
``` {r, include=FALSE}
source("tools/chunk-options.R")

knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

library(skimr)
library(tidyverse)
library(txtplot)
library(NostalgiR)

```

## 1. 콘솔에서 텍스트를 활용한 시각화

GUI가 일반화되기 이전에 데이터를 분석한 경험이 있는 분은 아마도 콘솔에서 그래프를 그려본 향수가 느껴질 수도 있다.
탐색적 데이터분석을 콘솔에서 가볍게 실행해 보는 방법을 살펴보자. 활용될 팩키지는 다음과 같다.


- [skimr](https://github.com/ropenscilabs/skimr): 텍스트 기반 요약 통계량 
- [txtplot](https://cran.r-project.org/web/packages/txtplot/index.html): 텍스트 기반 시각화 
- [NostalgiR: Advanced Text-Based Plots](https://cran.r-project.org/web/packages/NostalgiR/)

범주형 변수 시각화를 위한 막대그래프, 연속형 단변량 변수 시각화를 위한 분포(density), 
히스토그램(histogram), 상자그림(boxplot)이 우선 떠오르고, 시계열 데이터를 위한 자기상관 그래프, 
변수간 관계를 일별할 수 있는 산점도가 있다.

``` {r eda-text-txtplot}
# 0. 환경설정 -------------------------------------------------
# devtools::install_github("hadley/colformat")
# devtools::install_github("ropenscilabs/skimr")
# install.packages("txtplot")

library(skimr)
library(tidyverse)
library(txtplot)

## 2.1. 수식 그래프 --------------------------------------
txtcurve(log(x), 0.1, 4, xlab = "Log")
txtcurve(x^2, -4, 4, xlab = "x^2")

## 2.2. 막대 그래프 --------------------------------------
votes <- factor(c("기호1번", "기호1번", "기호1번", "기호2번", "기호2번", "기호3번"))

txtbarchart(votes, pch="+",  width = round(options()$width*0.7))

## 2.3. 상자그림 그래프 --------------------------------------
txtboxplot(rnorm(1000,0,0.5), rnorm(100, 1))

## 2.4. 분포 그래프 ------------------------------------------
txtdensity(rnorm(500), pch = "+")

## 2.5. 히스토그램 ------------------------------------------
nos.hist(rnorm(500), freq=TRUE)

## 2.6. 자기상관 그래프 ------------------------------------------
txtacf(arima.sim(list(ar = 0.7), n = 100))

## 2.7. 산점도 ------------------------------------------
txtplot(iris$Sepal.Length, iris$Sepal.Width, xlab="Sepal.Length", ylab="Sepal.Width")
```

